CREATE TABLE app_user (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name VARCHAR2(40) NOT NULL,
    full_name VARCHAR2(80) NOT NULL,
    email VARCHAR2(120) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    base_currency CHAR(3) DEFAULT 'INR' NOT NULL,
    profile_status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
    last_login_at TIMESTAMP,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_app_user_login UNIQUE (login_name),
    CONSTRAINT uq_app_user_email UNIQUE (email),
    CONSTRAINT chk_base_currency CHECK (LENGTH(base_currency) = 3),
    CONSTRAINT chk_profile_status CHECK (profile_status IN ('ACTIVE', 'LOCKED', 'ARCHIVED'))
);

CREATE TABLE account (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    account_name VARCHAR2(60) NOT NULL,
    account_type VARCHAR2(20) NOT NULL,
    opening_balance NUMBER(12,2) DEFAULT 0 NOT NULL,
    current_balance NUMBER(12,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_account_user FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_account_user_name UNIQUE (user_id, account_name),
    CONSTRAINT chk_account_type CHECK (account_type IN ('BANK', 'CARD', 'CASH', 'WALLET')),
    CONSTRAINT chk_account_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_account_balances CHECK (opening_balance >= 0 AND current_balance >= 0)
);

CREATE TABLE category (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(60) NOT NULL,
    category_type VARCHAR2(10) NOT NULL,
    default_monthly_limit NUMBER(12,2),
    is_system_generated CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT uq_category_name_type UNIQUE (category_name, category_type),
    CONSTRAINT chk_category_type CHECK (category_type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_category_limit CHECK (default_monthly_limit IS NULL OR default_monthly_limit >= 0),
    CONSTRAINT chk_category_system_flag CHECK (is_system_generated IN ('Y', 'N'))
);

CREATE TABLE transaction_entry (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    account_id NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    transaction_type VARCHAR2(10) NOT NULL,
    amount NUMBER(12,2) NOT NULL,
    transaction_date DATE NOT NULL,
    payment_mode VARCHAR2(20) NOT NULL,
    description VARCHAR2(180) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES account(account_id),
    CONSTRAINT fk_transaction_category FOREIGN KEY (category_id) REFERENCES category(category_id),
    CONSTRAINT chk_transaction_type CHECK (transaction_type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT chk_transaction_amount CHECK (amount > 0),
    CONSTRAINT chk_payment_mode CHECK (payment_mode IN ('UPI', 'CARD', 'BANK_TRANSFER', 'CASH'))
);

CREATE OR REPLACE VIEW vw_monthly_cashflow AS
SELECT
    user_id,
    TRUNC(transaction_date, 'MM') AS report_month,
    SUM(CASE WHEN transaction_type = 'INCOME' THEN amount ELSE 0 END) AS total_income,
    SUM(CASE WHEN transaction_type = 'EXPENSE' THEN amount ELSE 0 END) AS total_expense,
    SUM(CASE WHEN transaction_type = 'INCOME' THEN amount ELSE -amount END) AS net_cashflow
FROM transaction_entry
GROUP BY user_id, TRUNC(transaction_date, 'MM');
